apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  destination:
    namespace: strimzi-kafka
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: quay.io/strimzi-helm
    targetRevision: 0.44.0
    chart: strimzi-kafka-operator
    helm:
      valuesObject:
        watchAnyNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
