apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-backend
spec:
  selector:
    matchLabels:
      app: thanos-backend
  template:
    metadata:
      labels:
        app: thanos-backend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "thanos-backend"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: thanos-backend
        image: backend
        ports:
        - containerPort: 3000
        env:
        - name: TOPIC_NAME
          value: dad-jokes
        - name: PUBSUB_NAME
          value: pubsub
        - name: TOPIC_RESULT_NAME
          value: dad-jokes-result
        - name: OPENAI_API_KEY
          value: "changeme"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: thanos-secret-store
spec:
  provider:
    pulumi:
      organization: thanosnguyen
      environment: dev
      project: 01-idp
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secrets
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: thanos-secret-store
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: openai
      metadataPolicy: None
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: thanos-backend-scaledobject
spec:
  scaleTargetRef:
    name: thanos-backend
  pollingInterval: 10
  maxReplicaCount: 5
  minReplicaCount: 0
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: thanos-kafka-cluster-kafka-bootstrap.test.svc.cluster.local:9092
      consumerGroup: thanos-backend
      scaleToZeroOnInvalidOffset: "true"
      topic: dad-jokes
      lagThreshold: "5"
