apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-frontend-deployment
spec:
  selector:
    matchLabels:
      app: thanos-frontend
  template:
    metadata:
      labels:
        app: thanos-frontend
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "thanos-frontend"
        dapr.io/app-port: "6002"
    spec:
      containers:
      - name: thanos-frontend
        image: frontend
        ports:
        - containerPort: 3000
        env:
        - name: TOPIC_NAME
          value: dad-jokes-result
        - name: PUBSUB_NAME
          value: pubsub
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-frontend-service
spec:
  selector:
    app: thanos-frontend
  ports:
  - protocol: TCP
    port: 80        # Service port
    targetPort: 3000  # Container port
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-frontend-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dadjoke-wasmcon.ediri.online
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ingressClassName: nginx
  rules:
  - host: dadjoke-wasmcon.ediri.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thanos-frontend-service
            port:
              number: 80
