apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: ${{values.name}}-generator
spec:
  image: ${{values.name}}-generator-api
  executor: containerd-shim-spin
  replicas: 1
  checks: {}
  podLabels:
    "backstage.io/kubernetes-id": ${{values.name}}
  variables:
  - name: PUBSUB_NAME
    value: pubsub
  - name: TOPIC_NAME
    value: dad-jokes
  - name: DAPR_HTTP_PORT
    value: "3500"
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "${{values.name}}-generator"
    dapr.io/app-port: "80"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.name}}-generator-ingress
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${{values.name}}-api-wasmcon.ediri.online
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ingressClassName: nginx
  rules:
  - host: ${{values.name}}-api-wasmcon.ediri.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ${{values.name}}-generator
            port:
              number: 80
