apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: argocd
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: infra
  source:
  - repoURL: https://github.com/thanos-nguyen/thanos-idp.git
    targetRevision: HEAD
    path: gitops/cluster-addons/cnpg/manifest
  - repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.22.1
    chart: cloudnative-pg
  - repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.2.0
    chart: cluster
    helm:
      valuesObject:
        type: postgresql
        mode: standalone
        version:
          postgresql: "16"
        cluster:
          instances: 1
          initdb:
            owner: backstage
            postInitApplicationSQL:
            - ALTER ROLE backstage CREATEDB
            secret:
              name: cnpg-ns-cluster-secret
        backups:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
  ignoreDifferences:
  - group: postgresql.cnpg.io
    kind: Cluster
    namespace: backstage
    jqPathExpressions:
    - ".spec.postgresql.pg_hba"
    - ".spec.postgresql.pg_ident"
