apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: 'https://charts.external-secrets.io'
    targetRevision: 0.10.5
    chart: external-secrets
  - path: gitops/cluster-addons/external-secrets/provider
    targetRevision: main
    directory:
      recurse: true
    repoURL: https://github.com/thanos-nguyen/thanos-idp.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
