apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr-operator
  namespace: argocd
spec:
  destination:
    namespace: dapr-system
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - repoURL: https://dapr.github.io/helm-charts/
    targetRevision: 1.14.4
    chart: dapr
  - repoURL: https://dapr.github.io/helm-charts/
    targetRevision: 0.15.0
    chart: dapr-dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: dapr-scheduler-server
    namespace: dapr-system
    jqPathExpressions:
    - ".spec.volumeClaimTemplates[].apiVersion"
    - ".spec.volumeClaimTemplates[].kind"
