apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-provider-token
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore 
  data:
  - secretKey: cfat
    remoteRef:
      key: cloud.cf-api-token