apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-provider-token
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: cf-token-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        cf-token: "{{ .cf-api-token | toString }}"  
  data:
  - secretKey: cf-api-token
    remoteRef:
      key: cloud.cf-api-token