apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-ns-secret
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: db-secret-store
    kind: ClusterSecretStore
  target:
    name: cnpg-ns-cluster-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .user | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: user
    remoteRef:
      key: db.backstage.user
  - secretKey: password
    remoteRef:
      key: db.backstage.password