apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-secrets
spec:
  refreshInterval: 20s
  secretStoreRef:
    kind: ClusterSecretStore
    name: db-secret-store
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: "env"
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cnpg-secret
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: db-secret-store
    kind: ClusterSecretStore
  target:
    name: cnpg-cluster-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .user | toString }}"
        password: "{{ .password | toString }}"
  data:
  - secretKey: user
    remoteRef:
      key: db.backstage.user
  - secretKey: password
    remoteRef:
      key: db.backstage.password
