apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    pulumi:
      organization: thanosnguyen
      environment: 01-idp-dev
      project: thanos-idp
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: db-secret-store
spec:
  provider:
    pulumi:
      organization: thanosnguyen
      environment: db
      project: thanos-idp
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: default
