domainFilters:
  - "thanos.ip-ddns.com"

sources:
  - ingress

provider: cloudflare

policy: sync

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-provider-token
        key: cfat

logLevel: debug

extraArgs:
  - --cloudflare-proxied
  - --cloudflare-dns-records-per-page=5000
  - --default-targets=192.168.101.20