#domainFilters:
#- "thanos.ip-ddns.com"

sources:
  - service
  - ingress

provider: cloudflare

policy: sync

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-provider-token
        key: cfat