apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-operator
  namespace: argocd
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: infra
  sources:
  - path: gitops/cluster-addons/external-dns/config
    targetRevision: main
    directory:
      recurse: true
    repoURL: https://github.com/thanos-nguyen/thanos-idp.git
  - repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.15.0
    chart: external-dns
    helm:
      valueFiles:
      - $values/gitops/cluster-addons/external-dns/external-dns-values.yaml
  - repoURL: https://github.com/thanos-nguyen/thanos-idp.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
