apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-app
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx
    helm:
      valuesObject:
        serviceAccount:
          automountServiceAccountToken: true
        controller:
          publishService:
            enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
