apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-app
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.1
    chart: cert-manager
    helm:
      valuesObject:
        serviceAccount:
          automountServiceAccountToken: true
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
