apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-app
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://github.com/thanos-nguyen/thanos-idp.git
    targetRevision: HEAD
    path: gitops/cluster-addons/backstage/manifest
  - repoURL: https://github.com/thanos-nguyen/thanos-backstage.git
    targetRevision: main
    path: my-chart
    helm:
      valueFiles:
      - $values/gitops/cluster-addons/backstage/helm-values.yaml
  - repoURL: https://github.com/thanos-nguyen/thanos-idp.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
