backstage:
  serviceAccount:
    create: true
    name: backstage
  backstage:
    image:
      repository: ghcr.io/thanos-nguyen/thanos-backstage
      tag: 0.0.1
    extraEnvVarsSecrets:
      - backstage-secrets
    extraEnvVars:
      - name: NODE_ENV
        value: development
      - name: ARGOCD_URL
        value: "http://argocd.thanos.ip-ddns.com/api/v1/"
      - name: BASE_URL
        value: backstage-wasmcon.ediri.online
      - name: CATALOG_LOCATION
        value: "https://raw.githubusercontent.com/thanos-nguyen/thanos-idp/refs/heads/main/templates/catalog-all.yaml"
      - name: POSTGRES_HOST
        value: "backstage-app-cluster-rw"
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_USER
        value: "backstage"
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
              name: cnpg-secret
              key: db.backstage.password
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
  ingress:
    enabled: true
    annotations:
      "external-dns.alpha.kubernetes.io/hostname": backstage-wasmcon.ediri.online
      "external-dns.alpha.kubernetes.io/ttl": "60"
    className: nginx
    host: backstage-wasmcon.ediri.online
