apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-operator
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: infra
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.16.0
    chart: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
